### ISSUE TITLE
Possible issue in LAI calculation (from Hemiphot.R)

### ISSUE THREAD

**Issue by fwindram** [joathert/canofi-app#17]
In functions.js on line 232, the code is as follows:

 https://github.com/joathert/canofi-app/blob/df196d7fd8e7e17f8f380a685f37514349f08dae/functions.js#L232-L234

This means that the following angles (where `i=2` and `i=1`) are analysed twice:
```
[ 8 24 39 54 69]
[ 7 23 38 53 68]
```

and the angles they accidentally replace (where `i=-2` and `i=-1`) are never analysed:

```
[ 4 20 35 50 65]
[ 5 21 36 51 66]
```

To fix this, the line should probably instead read 

```python
for i in range(-6,7):
    angle_idx = angle + i - 1
    T +=  gap_fractions[angle_idx]
```

This could potentially be causing the difference in LAI estimate between the original R and the python equivalent that is noted in the README.

**Comment by joathert** [comment]
Thanks for spotting this @fwindram .
